openapi: 3.0.3
info:
  title: PC games openapi
  description: Api for PC games dataset
  version: 1.0.0
  contact:
    name: Mario Perhat
    email: mario.perhat@fer.hr
  license:
    name: CC0-1.0

paths:
  /api/game/{ime_igre}:
    get:
      summary: Get information about a game by name
      description: Returns information about a game by its name
      parameters:
        - name: ime_igre
          in: path
          description: Name of the game
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a game by name
      description: Deletes a game by name of the game
      parameters:
        - name: ime_igre
          in: path
          description: Name of the game
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/game/{ime_igre}/{nova_cijena}:
    put:
      summary: Update the price of a game
      description: Changes the price of a game by its name
      parameters:
        - name: ime_igre
          in: path
          description: Name of the game
          required: true
        - name: nova_cijena
          in: path
          description: New price for the game
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateGameResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/game:
    post:
      summary: Add a new game
      description: Creates a new game in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameDetails'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/games:
    get:
      summary: Get the entire collection of game data
      description: Returns detailed information about all games
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesCollectionResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/freegames:
    get:
      summary: Get information about free games
      description: Returns detailed information about games with a price of 0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesCollectionResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/pricerange/{minPrice}/{maxPrice}:
    get:
      summary: Get games within a specified price range
      description: Returns detailed information about games within the specified price range
      parameters:
        - name: minPrice
          in: path
          description: Minimum price
          required: true
        - name: maxPrice
          in: path
          description: Maximum price
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesCollectionResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GameResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the response
        message:
          type: string
          description: Additional message
        response:
          type: array
          items:
            $ref: '#/components/schemas/Game'
    Game:
      type: object
      properties:
        game_data:
          $ref: '#/components/schemas/GameDetails'
    GameDetails:
      type: object
      properties:
        zanr:
          type: string
          description: Genre of the game
        cijena:
          type: number
          description: Price of the game
        ocjena:
          type: number
          description: Rating of the game
        fransiza:
          type: string
          description: Franchise information
        ime_igre:
          type: string
          description: Name of the game
        developeri:
          type: array
          items:
            $ref: '#/components/schemas/Developer'
        ime_izdavac:
          type: string
          description: Name of the publisher
        multiplayer:
          type: boolean
          description: Indicates if the game supports multiplayer
        singleplayer:
          type: boolean
          description: Indicates if the game supports singleplayer
        datum_izdanja:
          type: string
          format: date
          description: Release date of the game (in the format YYYY-MM-DD)
        predvidjeni_br_sati_za_igranje:
          type: integer
          description: Estimated number of hours to complete the game
    Developer:
      type: object
      properties:
        developer:
          type: string
          description: Developer information
        godina_osnutka:
          type: integer
          description: Year of establishment of the developer
          schemas:
    UpdateGameResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the response
        message:
          type: string
          description: Additional message
        response:
          type: null  
    Error:
      type: object
      properties:
        status:
          type: string
          description: Status of the error response
        message:
          type: string
          description: Additional message
        response:
          type: null  
    SuccessResponse:
        type: object
        properties:
          message:
            type: string
            description: Success message
          data:
            $ref: '#/components/schemas/GameDetails'
    GamesCollectionResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the response
        message:
          type: string
          description: Additional message
        response:
          type: array
          items:
            $ref: '#/components/schemas/Game'